[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
core_sol_bond_stake_sc = "HtLmdHrUHszpc5i85NBHhrjtbkL5AFKThjCqrE9H1PYc"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/bucurdavid/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
