[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
core_sol_bond_stake_sc = "2sr4qeqsgTGQBdYRWSfaScapUfpB2JGtgiKjVEnneuKS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/markpaul/Documents/Source/Software/core-sol-bonding-staking-sc/devnet_wal_deployer_program_core_sol_bonding_staking_GoGkBc38gDYbsiw3HfkPCQvC4K9cuqLwqJ6hTAV7rG1p.json"

[scripts]
test = "yarn run ts-mocha --runInBand  -p ./tsconfig.json -t 1000000 tests/**/*.ts"


[test.validator]
[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"  
program = "tests/metaplex_token_metadata_program.so"


[[test.genesis]]
address = "BGUMAp9Gq7iTEuizy4pqaxsTyUCBK68MDfK752saRPUY"
program = "tests/bubble_gum_program.so"

[[test.genesis]]
address= "noopb9bkMVfRPU8AsbpTUg8AQkHtKwMYZiFUjNRtMmV"
program = "tests/logWrapper.so"

[[test.genesis]]
address= "cmtDvXumGCrqC1Age74AVPhSRVXJMd8PJS91L8KbNCK"
program = "tests/compression.so"
